
server:
  port: 8083

spring:
  application:
    name: OrderService

  jpa:
    hibernate:
      ddl- auto: update
      show- sql: false



  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver



